# Generated by Django 5.2.13 on 2026-06-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lesson_test_testquestion_questionoption_testresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
